name: fulfillment-protocol
channels:
- defaults
dependencies:
- boto3=1.4.4=py36_0
- botocore=1.5.47=py36_0
- docutils=0.13.1=py36_0
- jmespath=0.9.0=py36_0
- jsonschema=2.6.0=py36_0
- openssl=1.0.2k=2
- pip=9.0.1=py36_1
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- readline=6.2=2
- s3transfer=0.1.10=py36_0
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - arrow==0.10.0

